# Site settings
title: Oriģinālas Dāvanas
email: info@originalas-davanas.lv
#description: Visādas oriģinālas dāvanas
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://originalas-davanas.lv" # the base hostname & protocol for your site
twitter_username: OriginalaDavana

# Build settings
markdown: kramdown
# highlighter: rouge
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path:       ""
      type:       "posts"
    values:
      layout:     "post"
      category:   produkti

  -
      scope:
        path:       ""
        type:       "pages"
      values:
        layout:     "page"